#Requires -Version 5.1

<#
.SYNOPSIS
Toolbox picker: browse the script library, read what each script does, and copy one out.

.DESCRIPTION
Single self-contained file. Every script in the library is embedded in it together with its description, so it
works on a machine that does not have the repository (a jumpbox, a customer server). Pick a category, move
through the list to read the details, and press Enter to copy the selected script to the clipboard. Nothing is
run and nothing is installed. Paste the script into a .ps1 file (or press Tab to save it as a file) and run it
from there.

Keys: Up/Down/PageUp/PageDown move, Enter copies the script, F2 copies it as a scriptblock you can paste straight
into a console and run with & $Name -Param value, Tab saves it to a file, typing filters the list,
Backspace edits the filter, Esc clears the filter or goes back.

Generated by tools/Build-Toolbox.ps1. Do not edit the generated file; edit tools/Toolbox.template.ps1 or the
script headers and rebuild.

.PARAMETER List
Print the catalog (name, category, synopsis) and exit. Useful when the interactive picker is not available.

.PARAMETER Name
Copy (or with -OutFile, save) one script by name without opening the picker. Accepts the name with or without
its extension.

.PARAMETER OutFile
Used with -Name: write the script to this path instead of the clipboard.

.EXAMPLE
.\toolbox.ps1

.EXAMPLE
.\toolbox.ps1 -List

.EXAMPLE
.\toolbox.ps1 -Name Get-StaleUserAccount -OutFile C:\Temp\Get-StaleUserAccount.ps1

.NOTES
Platform:     Windows PowerShell 5.1 or PowerShell 7 (Windows, macOS, Linux)
Permissions:  None (reads nothing from disk; writes a file only when you save one)
When to use:  On a jumpbox or customer machine that has no copy of the repository.
Safety:       Read-only (copies text to the clipboard or writes the file you ask for)
Version:      2.0
#>
[CmdletBinding()]
param(
    [switch]$List,
    [string]$Name,
    [string]$OutFile
)

Set-StrictMode -Version Latest

#__TOOLBOX_DATA__

# ----------------------------------------------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------------------------------------------

function Get-ConsoleWidth {
    try {
        $w = [Console]::WindowWidth
        if ($w -lt 41) { return 80 }
        return [Math]::Min(($w - 1), 120)
    } catch { return 80 }
}

function Get-ConsoleHeight {
    try {
        $h = [Console]::WindowHeight
        if ($h -lt 15) { return 30 }
        return $h
    } catch { return 30 }
}

function Test-CanReadKeys {
    try { return (-not [Console]::IsInputRedirected) -and (-not [Console]::IsOutputRedirected) } catch { return $false }
}

function Get-ScriptText {
    param([Parameter(Mandatory)][psobject]$Entry)
    $bytes = [Convert]::FromBase64String($Entry.Data)
    $in = New-Object System.IO.MemoryStream (, $bytes)
    $gz = New-Object System.IO.Compression.GZipStream ($in, [System.IO.Compression.CompressionMode]::Decompress)
    $reader = New-Object System.IO.StreamReader ($gz, (New-Object System.Text.UTF8Encoding $false))
    try { return $reader.ReadToEnd() } finally { $reader.Dispose() }
}

function Get-WrappedLine {
    # "Label        text..." wrapped to Width, continuation lines indented under the text.
    param([string]$Label, [string]$Text, [int]$Width)
    $indent = 15
    $room = [Math]::Max(20, $Width - $indent)
    $out = New-Object System.Collections.Generic.List[string]
    $line = ''
    foreach ($word in ($Text -split '\s+')) {
        if (-not $word) { continue }
        if ($line -and (($line.Length + 1 + $word.Length) -gt $room)) {
            $out.Add($line)
            $line = $word
        } elseif ($line) {
            $line = "$line $word"
        } else {
            $line = $word
        }
    }
    if ($line) { $out.Add($line) }
    if ($out.Count -eq 0) { return @() }
    $result = @()
    for ($i = 0; $i -lt $out.Count; $i++) {
        $prefix = if ($i -eq 0) { ("  " + $Label).PadRight($indent) } else { ' ' * $indent }
        $result += ($prefix + $out[$i])
    }
    return $result
}

function Get-DetailLine {
    param([psobject]$Entry, [int]$Width)
    $lines = @()
    $lines += Get-WrappedLine 'What' $Entry.Synopsis $Width
    if ($Entry.When)     { $lines += Get-WrappedLine 'When to use' $Entry.When $Width }
    if ($Entry.Safety)   { $lines += Get-WrappedLine 'Safety' $Entry.Safety $Width }
    if ($Entry.Perms)    { $lines += Get-WrappedLine 'Permissions' $Entry.Perms $Width }
    if ($Entry.Platform) { $lines += Get-WrappedLine 'Platform' $Entry.Platform $Width }
    if ($Entry.Modules)  { $lines += Get-WrappedLine 'Modules' $Entry.Modules $Width }
    if ($Entry.Params.Count -gt 0) { $lines += Get-WrappedLine 'Parameters' ($Entry.Params -join ', ') $Width }
    if ($Entry.Example)  { $lines += Get-WrappedLine 'Example' $Entry.Example $Width }
    if ($lines.Count -gt 12) { $lines = @($lines[0..10]) + '               ...' }
    return $lines
}

function Save-ScriptFile {
    param([psobject]$Entry, [string]$Path)
    $text = Get-ScriptText $Entry
    # PowerShell 5.1 reads a BOM-less file as ANSI, so .ps1 gets a BOM; bash/Python must not have one.
    $bom = $Entry.Name -like '*.ps1'
    $enc = New-Object System.Text.UTF8Encoding $bom
    [System.IO.File]::WriteAllText($Path, $text, $enc)
}

function Get-BlockVariable {
    param([psobject]$Entry)
    '$' + ([IO.Path]::GetFileNameWithoutExtension($Entry.Name) -replace '[^A-Za-z0-9]', '_')
}

function Copy-ScriptToClipboard {
    # Returns $true when the text reached the clipboard. -AsBlock wraps a PowerShell script as
    # "$Name = { ... }" so pasting it into a console defines it; run it with: & $Name -Param value
    param([psobject]$Entry, [switch]$AsBlock)
    $text = Get-ScriptText $Entry
    if ($AsBlock) { $text = "$(Get-BlockVariable $Entry) = {`r`n$text`r`n}`r`n" }
    try {
        if (Get-Command Set-Clipboard -ErrorAction SilentlyContinue) {
            Set-Clipboard -Value $text
            return $true
        }
        if (Get-Command pbcopy -ErrorAction SilentlyContinue) { $text | & pbcopy; return $true }
        if (Get-Command xclip -ErrorAction SilentlyContinue)  { $text | & xclip -selection clipboard; return $true }
    } catch { }
    return $false
}

function Get-FreePath {
    param([string]$Folder, [string]$FileName)
    $path = Join-Path $Folder $FileName
    if (-not (Test-Path -LiteralPath $path)) { return $path }
    $base = [IO.Path]::GetFileNameWithoutExtension($FileName)
    $ext = [IO.Path]::GetExtension($FileName)
    $n = 1
    while (Test-Path -LiteralPath (Join-Path $Folder "$base-$n$ext")) { $n++ }
    return (Join-Path $Folder "$base-$n$ext")
}

function Invoke-EntryAction {
    # Enter = copy, Tab = save. Returns a status line for the picker footer.
    param([psobject]$Entry, [ValidateSet('Copy', 'Block', 'Save')][string]$Mode)
    if ($Mode -eq 'Block') {
        if ($Entry.Kind -ne 'PowerShell') {
            return @{ Ok = $false; Text = 'Scriptblock copy is for PowerShell scripts only. Use Enter to copy the text.' }
        }
        if (Copy-ScriptToClipboard $Entry -AsBlock) {
            $v = Get-BlockVariable $Entry
            return @{ Ok = $true; Text = "Copied as scriptblock. Paste it, then run:  & $v -Param value" }
        }
        $Mode = 'Save'
    }
    if ($Mode -eq 'Copy') {
        if (Copy-ScriptToClipboard $Entry) {
            return @{ Ok = $true; Text = "Copied $($Entry.Name) ($($Entry.Lines) lines) to the clipboard. Paste it into a file or console." }
        }
        $Mode = 'Save'
    }
    $path = Get-FreePath (Get-Location).Path $Entry.Name
    try {
        Save-ScriptFile $Entry $path
        return @{ Ok = $true; Text = "Saved $path" }
    } catch {
        return @{ Ok = $false; Text = "Could not save $path : $($_.Exception.Message)" }
    }
}

# ----------------------------------------------------------------------------------------------------------------
# Picker
# ----------------------------------------------------------------------------------------------------------------

function Show-Picker {
    <#
    Rows are objects with Label, Search, Entry (script) or Payload (anything). When -Scripts is set, Enter copies
    and Tab saves, and the detail pane describes the highlighted script. Otherwise Enter returns the row.
    Returns the chosen row, or $null for Back/Esc.
    #>
    param(
        [string]$Title,
        [object[]]$Rows,
        [switch]$Scripts,
        [string]$Banner
    )

    $filter = ''; $sel = 0; $top = 0; $prev = 0; $status = $null
    Clear-Host
    while ($true) {
        $view = if ($filter) {
            @($Rows | Where-Object { $_.Search.IndexOf($filter, [StringComparison]::OrdinalIgnoreCase) -ge 0 })
        } else { @($Rows) }
        if ($sel -ge $view.Count) { $sel = [Math]::Max(0, $view.Count - 1) }

        $w = Get-ConsoleWidth; $h = Get-ConsoleHeight
        $detail = @()
        if ($Scripts -and $view.Count -gt 0) { $detail = @(Get-DetailLine $view[$sel].Entry $w) }
        $listH = [Math]::Max(3, $h - ($detail.Count + 7))
        if ($sel -lt $top) { $top = $sel }
        if ($sel -ge ($top + $listH)) { $top = $sel - $listH + 1 }
        if ($top -lt 0) { $top = 0 }

        $out = New-Object System.Collections.Generic.List[object]
        $out.Add(@{ T = "  $Title"; C = 'White' })
        if ($Banner) { $out.Add(@{ T = "  $Banner"; C = 'DarkGray' }) } else { $out.Add(@{ T = ''; C = 'Gray' }) }
        $out.Add(@{ T = ('-' * $w); C = 'DarkGray' })
        if ($view.Count -eq 0) {
            $out.Add(@{ T = '   (nothing matches the filter)'; C = 'Yellow' })
        } else {
            $last = [Math]::Min($view.Count - 1, $top + $listH - 1)
            for ($i = $top; $i -le $last; $i++) {
                $mark = if ($i -eq $sel) { ' > ' } else { '   ' }
                $out.Add(@{ T = ($mark + $view[$i].Label); C = $(if ($i -eq $sel) { 'Cyan' } else { 'Gray' }) })
            }
        }
        if ($Scripts) {
            $out.Add(@{ T = ('-' * $w); C = 'DarkGray' })
            foreach ($d in $detail) { $out.Add(@{ T = $d; C = 'DarkGray' }) }
        }
        $out.Add(@{ T = ('-' * $w); C = 'DarkGray' })
        if ($status) {
            $out.Add(@{ T = "  $($status.Text)"; C = $(if ($status.Ok) { 'Green' } else { 'Red' }) })
        } else {
            $keys = if ($Scripts) { 'Enter copy | F2 copy as scriptblock | Tab save | type to filter | Esc back' } else { 'Enter open | type to filter | Esc quit' }
            $f = if ($filter) { "   filter: $filter   ($($view.Count) match)" } else { '' }
            $out.Add(@{ T = "  $keys$f"; C = 'DarkGray' })
        }

        [Console]::SetCursorPosition(0, 0)
        foreach ($l in $out) {
            $t = [string]$l.T
            if ($t.Length -gt $w) { $t = $t.Substring(0, $w - 3) + '...' }
            Write-Host $t.PadRight($w) -ForegroundColor $l.C
        }
        for ($i = $out.Count; $i -lt $prev; $i++) { Write-Host (' ' * $w) }
        $prev = $out.Count
        $status = $null

        $key = [Console]::ReadKey($true)
        switch ($key.Key) {
            'UpArrow'    { if ($sel -gt 0) { $sel-- } }
            'DownArrow'  { if ($sel -lt $view.Count - 1) { $sel++ } }
            'PageUp'     { $sel = [Math]::Max(0, $sel - $listH) }
            'PageDown'   { $sel = [Math]::Min([Math]::Max(0, $view.Count - 1), $sel + $listH) }
            'Home'       { $sel = 0 }
            'End'        { $sel = [Math]::Max(0, $view.Count - 1) }
            'Backspace'  { if ($filter) { $filter = $filter.Substring(0, $filter.Length - 1); $sel = 0; $top = 0 } }
            'Escape'     { if ($filter) { $filter = ''; $sel = 0; $top = 0 } else { return $null } }
            'Enter' {
                if ($view.Count -gt 0) {
                    if ($Scripts) { $status = Invoke-EntryAction $view[$sel].Entry 'Copy' } else { return $view[$sel] }
                }
            }
            'F2' {
                if ($Scripts -and $view.Count -gt 0) { $status = Invoke-EntryAction $view[$sel].Entry 'Block' }
            }
            'Tab' {
                if ($Scripts -and $view.Count -gt 0) { $status = Invoke-EntryAction $view[$sel].Entry 'Save' }
            }
            default {
                $c = $key.KeyChar
                if ($c -and -not [char]::IsControl($c)) { $filter += $c; $sel = 0; $top = 0 }
            }
        }
    }
}

function Show-NumberedPicker {
    # Fallback when keys cannot be read (redirected input, some hosts): numbered list, type a number to copy.
    param([string]$Title, [object[]]$Rows)
    while ($true) {
        Write-Host "`n  $Title" -ForegroundColor White
        for ($i = 0; $i -lt $Rows.Count; $i++) { Write-Host ("  {0,3}) {1}" -f ($i + 1), $Rows[$i].Label) }
        $answer = Read-Host "Number to select, blank to go back"
        if (-not $answer) { return $null }
        if ($answer -match '^\d+$' -and [int]$answer -ge 1 -and [int]$answer -le $Rows.Count) { return $Rows[[int]$answer - 1] }
        Write-Host '  Not a valid number.' -ForegroundColor Yellow
    }
}

function Find-ToolboxEntry {
    param([string]$Wanted)
    $stem = [IO.Path]::GetFileNameWithoutExtension($Wanted)
    @($Script:Toolbox | Where-Object {
        $_.Name -ieq $Wanted -or [IO.Path]::GetFileNameWithoutExtension($_.Name) -ieq $stem
    })
}

# ----------------------------------------------------------------------------------------------------------------
# Entry points
# ----------------------------------------------------------------------------------------------------------------

if ($List) {
    $Script:Toolbox | Sort-Object CategoryName, Name |
        Select-Object @{ n = 'Category'; e = { $_.CategoryName } }, Name, Synopsis |
        Format-Table -AutoSize -Wrap
    return
}

if ($Name) {
    $found = Find-ToolboxEntry $Name
    if ($found.Count -eq 0) { Write-Error "No script named '$Name'. Run with -List to see them."; return }
    if ($found.Count -gt 1) { Write-Error "'$Name' matches more than one script: $($found.Name -join ', ')"; return }
    if ($OutFile) {
        Save-ScriptFile $found[0] $OutFile
        Write-Host "Saved $OutFile"
    } elseif (Copy-ScriptToClipboard $found[0]) {
        Write-Host "Copied $($found[0].Name) to the clipboard."
    } else {
        Write-Error 'No clipboard available. Use -OutFile to write the script to a file.'
    }
    return
}

$banner = "$($Script:Toolbox.Count) scripts | built $Script:ToolboxBuilt"
$categories = @($Script:Toolbox | Group-Object CategoryName | Sort-Object Name)

if (-not (Test-CanReadKeys)) {
    Write-Host 'No interactive keyboard here, using the numbered list. Use -List or -Name for scripted use.' -ForegroundColor Yellow
    $catRows = @($categories | ForEach-Object { [pscustomobject]@{ Label = "$($_.Name) ($($_.Count))"; Payload = $_ } })
    $cat = Show-NumberedPicker 'Category' $catRows
    if (-not $cat) { return }
    $rows = @($cat.Payload.Group | Sort-Object Name | ForEach-Object { [pscustomobject]@{ Label = "$($_.Name) - $($_.Synopsis)"; Entry = $_ } })
    $pick = Show-NumberedPicker $cat.Payload.Name $rows
    if ($pick) {
        if (Copy-ScriptToClipboard $pick.Entry) { Write-Host "Copied $($pick.Entry.Name) to the clipboard." }
        else { $p = Get-FreePath (Get-Location).Path $pick.Entry.Name; Save-ScriptFile $pick.Entry $p; Write-Host "Saved $p" }
    }
    return
}

$catRows = @()
$catRows += [pscustomobject]@{
    Label = "All scripts ($($Script:Toolbox.Count))"; Search = 'all scripts'; Payload = $null
}
foreach ($g in $categories) {
    $catRows += [pscustomobject]@{ Label = "$($g.Name) ($($g.Count))"; Search = $g.Name; Payload = $g }
}

try {
    while ($true) {
        $cat = Show-Picker -Title 'Toolbox: select a category' -Rows $catRows -Banner $banner
        if (-not $cat) { break }
        $pool = if ($cat.Payload) { @($cat.Payload.Group) } else { @($Script:Toolbox) }
        $rows = @($pool | Sort-Object Name | ForEach-Object {
            [pscustomobject]@{
                Label  = "$($_.Name)  -  $($_.Synopsis)"
                Search = "$($_.Name) $($_.Synopsis) $($_.CategoryName) $($_.When)"
                Entry  = $_
            }
        })
        $title = if ($cat.Payload) { $cat.Payload.Name } else { 'All scripts' }
        [void](Show-Picker -Title $title -Rows $rows -Scripts -Banner $banner)
    }
} finally {
    Clear-Host
}
